### ISSUE TITLE
Getting this error when calling make

### ISSUE THREAD

**Issue by tartavull** [seung-lab/segascorus#7]
```
  seg-error git:(0e92b9b) make
python setup.py build_ext --inplace
Compiling cy.pyx because it changed.
Cythonizing cy.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    int si, int sj, int sk, bint two_dim):
    '''Returns a list of 4-connectivity neighbors within a 2d image'''

    # Init
    cdef list res = []
    cdef int[3] orig = (i, j, k)
        ^
------------------------------------------------------------

cy.pyx:209:9: Assignment to non-lvalue 'orig'

Error compiling Cython file:
------------------------------------------------------------
...
    '''Returns a list of 4-connectivity neighbors within a 2d image'''

    # Init
    cdef list res = []
    cdef int[3] orig = (i, j, k)
    cdef int[3] shape = (si, sj, sk)
        ^
------------------------------------------------------------

cy.pyx:210:9: Assignment to non-lvalue 'shape'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef int[3] shape = (si, sj, sk)

    #Index order: z,y,x
    cdef int dim

    cdef int[2] twod_dims = (1,2)
        ^
------------------------------------------------------------

cy.pyx:215:9: Assignment to non-lvalue 'twod_dims'

Error compiling Cython file:
------------------------------------------------------------
...

    #Index order: z,y,x
    cdef int dim

    cdef int[2] twod_dims = (1,2)
    cdef int[3] threed_dims = (0,1,2)
        ^
------------------------------------------------------------

cy.pyx:216:9: Assignment to non-lvalue 'threed_dims'

Error compiling Cython file:
------------------------------------------------------------
...

    cdef int[3] candidate

    for dim in threed_dims:

        candidate = (orig[0], orig[1], orig[2])
                 ^
------------------------------------------------------------

cy.pyx:222:18: Assignment to non-lvalue 'candidate'

Error compiling Cython file:
------------------------------------------------------------
...

        candidate = (orig[0], orig[1], orig[2])
        candidate[dim] = candidate[dim] + 1

        if candidate[dim] < shape[dim]:
            res.append(candidate)
                               ^
------------------------------------------------------------

cy.pyx:226:32: Cannot convert 'int [3]' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        candidate[dim] = candidate[dim] + 1

        if candidate[dim] < shape[dim]:
            res.append(candidate)

        candidate = (orig[0], orig[1], orig[2])
                 ^
------------------------------------------------------------

cy.pyx:228:18: Assignment to non-lvalue 'candidate'

Error compiling Cython file:
------------------------------------------------------------
...

        candidate = (orig[0], orig[1], orig[2])
        candidate[dim] = candidate[dim] - 1

        if 0 <= candidate[dim]:
            res.append(candidate)
                               ^
------------------------------------------------------------

cy.pyx:232:32: Cannot convert 'int [3]' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    cdef np.ndarray[DTYPE_t, ndim=3] res = np.empty((s0, s1, s2), dtype=DTYPE)
    cdef int z,y,x, num_neighbors
    cdef list neighbor_indices
    cdef DTYPE_t val
    #a structure holding the maximum number of neighbors for 3d connectivity
    cdef DTYPE_t[6] neighbor_values = (0,0,0,0,0,0)
        ^
------------------------------------------------------------

cy.pyx:265:9: Assignment to non-lvalue 'neighbor_values'
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    ext_modules = cythonize("*.pyx")
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 840, in cythonize
    cythonize_one(*args[1:])
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cy.pyx
make: *** [cy] Error 1
```

**Comment by tartavull** [comment]
nvm, probably missing some dependency, it worked now.
