### ISSUE TITLE
Any ideas why am I getting this? 

### ISSUE THREAD

**Issue by tartavull** [seung-lab/segascorus#8]
```
Submodule path 'seg-error': checked out '0e92b9be76fc06990084409b087e2af4fa3494cb'
make: Entering directory `/home/travis/.julia/v0.4/Agglomerator/deps/seg-error'
python setup.py build_ext --inplace
Compiling cy.pyx because it changed.
Cythonizing cy.pyx
Error compiling Cython file:
------------------------------------------------------------
...
        if 0 <= candidate[dim]:
            res.append(candidate)
    return res
cdef bint all_equal(DTYPE_t[:] arr, int length, DTYPE_t value):
                           ^
------------------------------------------------------------
cy.pyx:236:28: Expected an identifier or literal
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    ext_modules = cythonize("*.pyx")
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 517, in cythonize
    cythonize_one(pyx_file, c_file, quiet, options)
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 540, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cy.pyx
make: *** [cy] Error 1
make: Leaving directory `/home/travis/.julia/v0.4/Agglomerator/deps/seg-error'
```

**Comment by nicholasturner1** [comment]
Not exactly, but that's a decently old commit of the code. Try updating?

**Comment by tartavull** [comment]
It seems like I'm also using an old cython
Cython version 0.15.1

**Comment by tartavull** [comment]
Updating doesn't seem to have worked

```
Submodule 'deps/seg-error' (https://github.com/seung-lab/segerror.git) registered for path 'seg-error'
Cloning into 'deps/seg-error'...
remote: Counting objects: 80, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 80 (delta 12), reused 0 (delta 0), pack-reused 55
Unpacking objects: 100% (80/80), done.
Checking connectivity... done.
Submodule path 'seg-error': checked out 'a2a854e7b56d2efe4270faab0784da0578efb3fe'
Cython version 0.15.1
make: Entering directory `/home/travis/.julia/v0.4/Agglomerator/deps/seg-error'
python setup.py build_ext --inplace
Compiling cy.pyx because it changed.
Cythonizing cy.pyx
Error compiling Cython file:
------------------------------------------------------------
...
        if 0 <= candidate[dim]:
            res.append(candidate)
    return res
cdef bint all_equal(DTYPE_t[:] arr, int length, DTYPE_t value):
                           ^
------------------------------------------------------------
cy.pyx:323:28: Expected an identifier or literal
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    ext_modules = cythonize("*.pyx")
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 517, in cythonize
    cythonize_one(pyx_file, c_file, quiet, options)
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 540, in cythonize_one
    raise CompileError(None, pyx_file)
```

**Comment by tartavull** [comment]
I updated cython , by getting using pip.(Cython version 0.23.4)
The version in ubuntu repositories it is too old to compile.

**Comment by nicholasturner1** [comment]
OK. In the worst case (or at least temporarily) you can comment out that function entirely. It's only there for future functionality

**Comment by tartavull** [comment]
It know works correctly with new cython version

**Comment by tartavull** [comment]
I was able to reproduce locally that it doesn't compile under Cython version 0.15.1
